### ISSUE TITLE
有几个cookie问题

### ISSUE THREAD

**Issue by HuiJiOnGit** [xiaoxiaotank/XXTk.Auth.Samples#1]
你好：
 下载了cookie部分的代码试了下，有几个地方不明白

- 为什么在某个页面停留一会之后，会出现这两个cookie `ai_session` ，`ai_user` 但是我没有在控制台中找到set-cookie的响应

另外看了你的代码才知道原来将cookie内容保存到session中不需要引入session中间件的，涨知识了。
不过session中间件也有一些Cookie的选项配置，是不是说Session中间件的内容获取其实不依赖认证方案中使用的那个Cookie？

**Comment by HuiJiOnGit** [comment]
有取消注释一部分代码，启用了redis的部分，无其他修改

**Comment by xiaoxiaotank** [comment]
> 你好： 下载了cookie部分的代码试了下，有几个地方不明白
> 
> * 为什么在某个页面停留一会之后，会出现这两个cookie `ai_session` ，`ai_user` 但是我没有在控制台中找到set-cookie的响应
> 
> 另外看了你的代码才知道原来将cookie内容保存到session中不需要引入session中间件的，涨知识了。 不过session中间件也有一些Cookie的选项配置，是不是说Session中间件的内容获取其实不依赖认证方案中使用的那个Cookie？

**Comment by xiaoxiaotank** [comment]
第一个问题：
`ai_session` ，`ai_user`这个似乎和[ApplicationInsights-JS](https://github.com/Microsoft/ApplicationInsights-JS)有点关系，不过我对它不太了解，应该是浏览器设置的cookie

第二个问题：
首先要明确一下，session不是一个特定的数据结构，它就是“会话”的抽象表示。身份认证相关的信息存储在服务端，就是身份认证session，当然也可以把一些其他的会话信息存储到服务端。

因此，由于该仓库的示例代码是和身份认证相关的，所以那个cookie也是用于身份验证的cookie，因此里面所用到的sessionstore也仅仅只会存储身份认证的ticket，这个完全是由我们自己通过实现`ITicketStore`接口来达成目的的。

而session，可以自由使用，无需和身份认证关联起来，向存什么存什么。

**Comment by HuiJiOnGit** [comment]
明白了，谢谢你的解答
